# Generated by Django 5.1.1 on 2025-07-01 04:40

import chats_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0002_vectorstorewikipediaflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sources',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AddField(
            model_name='message',
            name='sources',
            field=models.JSONField(blank=True, default=chats_app.models.str_default_dict),
        ),
    ]
