# Generated by Django 5.1.3 on 2025-07-18 13:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats_app', '0003_remove_message_sources_delete_source_message_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats_app.conversation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
