# Generated by Django 5.1.3 on 2025-07-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationnote',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationnote',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='conversation_notes',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='category',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='ConversationNote',
        ),
        migrations.DeleteModel(
            name='NoteBook',
        ),
        migrations.DeleteModel(
            name='NoteCategory',
        ),
    ]
